spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/smart-home-iot}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://your-auth-server}

server:
  port: 8080

logging:
  level:
    root: INFO
    com.smarthome: DEBUG 